### ISSUE TITLE
indentation support?

### ISSUE THREAD

**Issue by danrlu** [peterk87/sublime-nextflow#8]
First of all thanks for this package. Hugely helpful and I've been using it since early 2020!

I don't know whether this is within the scope for this package so please feel free to close it. I often lose track of indentation with Nextflow code so was hoping for some auto formatting, but Sublime Edit > Line > Reindent doesn't do it quite right. For example, Sublime reindent will give this:
```
workflow {

  if (params.se) {

    fq = Channel.fromPath("${params.input_folder}/*.fq.gz")
    fq | fastp

    } else {

      fq = Channel.fromFilePairs("${params.input_folder}/*_{1,2}.fq.gz", flat: true)
      fq | fastp

    }

  }
```
Whereas I thought best practice would be:
```
workflow {

  if (params.se) {

    fq = Channel.fromPath("${params.input_folder}/*.fq.gz")
    fq | fastp

  } else {

    fq = Channel.fromFilePairs("${params.input_folder}/*_{1,2}.fq.gz", flat: true)
    fq | fastp

  }

}
```

Just leaving a note in case this is of interest. Thanks!

**Comment by peterk87** [comment]
Thanks for submitting the issue. It's been a minor annoyance for me when working with a few languages in ST, so I haven't put much time into trying to resolve it and generally avoid automatically reindenting lines when working in ST.

When putting together the plugin, I used the Groovy language syntax spec and added the Nextflow syntax spec to it. From my testing, it looks like the reindentation issue is present when working with Groovy and somebody else has also noted and reported the issue (https://github.com/sublimehq/Packages/issues/654).

It seems like putting `else` on a separate line avoids the reindentation issue:

```nextflow
workflow {

  if (params.se) {

    fq = Channel.fromPath("${params.input_folder}/*.fq.gz")
    fq | fastp

  } 
  else {

    fq = Channel.fromFilePairs("${params.input_folder}/*_{1,2}.fq.gz", flat: true)
    fq | fastp

  }

}
```

**Comment by danrlu** [comment]
That all makes sense and great to know how things work under the hood. Thanks very much!
